PK_DRUG_DATA = {
    "warfarin": {
        "half_life_hours": 40.0,
        "bioavailability": 0.99,
        "volume_of_distribution": 0.14,
        "protein_binding": 0.99,
        "clearance_pathway": "hepatic",
        "cyp_substrate": ["CYP2C9", "CYP3A4"],
        "cyp_inhibitor": [],
        "cyp_inducer": [],
        "therapeutic_range_low": 1.0,
        "therapeutic_range_high": 3.0,
        "molecular_weight": 308.3,
        "drug_class": "Anticoagulant"
    },
    "aspirin": {
        "half_life_hours": 0.25,
        "bioavailability": 0.68,
        "volume_of_distribution": 0.15,
        "protein_binding": 0.80,
        "clearance_pathway": "hepatic",
        "cyp_substrate": [],
        "cyp_inhibitor": [],
        "cyp_inducer": [],
        "therapeutic_range_low": 150.0,
        "therapeutic_range_high": 300.0,
        "molecular_weight": 180.2,
        "drug_class": "NSAID/Antiplatelet"
    },
    "metformin": {
        "half_life_hours": 6.5,
        "bioavailability": 0.55,
        "volume_of_distribution": 3.5,
        "protein_binding": 0.0,
        "clearance_pathway": "renal",
        "cyp_substrate": [],
        "cyp_inhibitor": [],
        "cyp_inducer": [],
        "therapeutic_range_low": 1.0,
        "therapeutic_range_high": 4.0,
        "molecular_weight": 165.6,
        "drug_class": "Biguanide"
    },
    "simvastatin": {
        "half_life_hours": 2.0,
        "bioavailability": 0.05,
        "volume_of_distribution": 3.0,
        "protein_binding": 0.95,
        "clearance_pathway": "hepatic",
        "cyp_substrate": ["CYP3A4"],
        "cyp_inhibitor": [],
        "cyp_inducer": [],
        "therapeutic_range_low": 0.002,
        "therapeutic_range_high": 0.05,
        "molecular_weight": 418.6,
        "drug_class": "Statin"
    },
    "amiodarone": {
        "half_life_hours": 1680.0,
        "bioavailability": 0.46,
        "volume_of_distribution": 60.0,
        "protein_binding": 0.996,
        "clearance_pathway": "hepatic",
        "cyp_substrate": ["CYP3A4", "CYP2C8"],
        "cyp_inhibitor": ["CYP2C9", "CYP3A4", "CYP2D6"],
        "cyp_inducer": [],
        "therapeutic_range_low": 1.0,
        "therapeutic_range_high": 2.5,
        "molecular_weight": 645.3,
        "drug_class": "Antiarrhythmic"
    },
    "lisinopril": {
        "half_life_hours": 12.0,
        "bioavailability": 0.25,
        "volume_of_distribution": 1.0,
        "protein_binding": 0.0,
        "clearance_pathway": "renal",
        "cyp_substrate": [],
        "cyp_inhibitor": [],
        "cyp_inducer": [],
        "therapeutic_range_low": 0.02,
        "therapeutic_range_high": 0.10,
        "molecular_weight": 405.5,
        "drug_class": "ACE Inhibitor"
    },
    "metoprolol": {
        "half_life_hours": 4.5,
        "bioavailability": 0.50,
        "volume_of_distribution": 5.6,
        "protein_binding": 0.12,
        "clearance_pathway": "hepatic",
        "cyp_substrate": ["CYP2D6"],
        "cyp_inhibitor": [],
        "cyp_inducer": [],
        "therapeutic_range_low": 0.05,
        "therapeutic_range_high": 0.20,
        "molecular_weight": 267.4,
        "drug_class": "Beta-blocker"
    },
    "digoxin": {
        "half_life_hours": 36.0,
        "bioavailability": 0.70,
        "volume_of_distribution": 7.3,
        "protein_binding": 0.25,
        "clearance_pathway": "renal",
        "cyp_substrate": [],
        "cyp_inhibitor": [],
        "cyp_inducer": [],
        "therapeutic_range_low": 0.0008,
        "therapeutic_range_high": 0.002,
        "molecular_weight": 780.9,
        "drug_class": "Cardiac Glycoside"
    },
    "fluconazole": {
        "half_life_hours": 30.0,
        "bioavailability": 0.90,
        "volume_of_distribution": 0.65,
        "protein_binding": 0.11,
        "clearance_pathway": "renal",
        "cyp_substrate": ["CYP3A4"],
        "cyp_inhibitor": ["CYP2C9", "CYP3A4", "CYP2C19"],
        "cyp_inducer": [],
        "therapeutic_range_low": 2.0,
        "therapeutic_range_high": 8.0,
        "molecular_weight": 306.3,
        "drug_class": "Antifungal"
    },
    "ibuprofen": {
        "half_life_hours": 2.0,
        "bioavailability": 0.87,
        "volume_of_distribution": 0.15,
        "protein_binding": 0.99,
        "clearance_pathway": "hepatic",
        "cyp_substrate": ["CYP2C9"],
        "cyp_inhibitor": ["CYP2C9"],
        "cyp_inducer": [],
        "therapeutic_range_low": 10.0,
        "therapeutic_range_high": 50.0,
        "molecular_weight": 206.3,
        "drug_class": "NSAID"
    },
    "omeprazole": {
        "half_life_hours": 1.5,
        "bioavailability": 0.65,
        "volume_of_distribution": 0.34,
        "protein_binding": 0.97,
        "clearance_pathway": "hepatic",
        "cyp_substrate": ["CYP2C19", "CYP3A4"],
        "cyp_inhibitor": ["CYP2C19"],
        "cyp_inducer": [],
        "therapeutic_range_low": 0.5,
        "therapeutic_range_high": 2.0,
        "molecular_weight": 345.4,
        "drug_class": "Proton Pump Inhibitor"
    },
    "clopidogrel": {
        "half_life_hours": 6.0,
        "bioavailability": 0.50,
        "volume_of_distribution": 0.5,
        "protein_binding": 0.98,
        "clearance_pathway": "hepatic",
        "cyp_substrate": ["CYP2C19", "CYP3A4"],
        "cyp_inhibitor": [],
        "cyp_inducer": [],
        "therapeutic_range_low": 0.001,
        "therapeutic_range_high": 0.05,
        "molecular_weight": 321.8,
        "drug_class": "Antiplatelet"
    },
    "lithium": {
        "half_life_hours": 24.0,
        "bioavailability": 1.0,
        "volume_of_distribution": 0.7,
        "protein_binding": 0.0,
        "clearance_pathway": "renal",
        "cyp_substrate": [],
        "cyp_inhibitor": [],
        "cyp_inducer": [],
        "therapeutic_range_low": 0.6,
        "therapeutic_range_high": 1.2,
        "molecular_weight": 6.9,
        "drug_class": "Mood Stabilizer"
    },
    "phenytoin": {
        "half_life_hours": 22.0,
        "bioavailability": 0.90,
        "volume_of_distribution": 0.75,
        "protein_binding": 0.90,
        "clearance_pathway": "hepatic",
        "cyp_substrate": ["CYP2C9", "CYP2C19"],
        "cyp_inhibitor": [],
        "cyp_inducer": ["CYP3A4", "CYP2C9"],
        "therapeutic_range_low": 10.0,
        "therapeutic_range_high": 20.0,
        "molecular_weight": 252.3,
        "drug_class": "Anticonvulsant"
    },
    "methotrexate": {
        "half_life_hours": 10.0,
        "bioavailability": 0.70,
        "volume_of_distribution": 0.9,
        "protein_binding": 0.50,
        "clearance_pathway": "renal",
        "cyp_substrate": [],
        "cyp_inhibitor": [],
        "cyp_inducer": [],
        "therapeutic_range_low": 0.01,
        "therapeutic_range_high": 0.10,
        "molecular_weight": 454.4,
        "drug_class": "Antimetabolite/DMARD"
    }
}
